//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Partial.WSCustomer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DominoSoapBinding", Namespace="urn:DefaultNamespace")]
    public partial class GetCustomersPartialService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GETCUSTOMERSPARTIALOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetCustomersPartialService() {
            this.Url = global::Partial.Properties.Settings.Default.PartialBeta_WSCustomer_GetCustomersPartialService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GETCUSTOMERSPARTIALCompletedEventHandler GETCUSTOMERSPARTIALCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:DefaultNamespace", ResponseNamespace="urn:DefaultNamespace")]
        [return: System.Xml.Serialization.SoapElementAttribute("GETCUSTOMERSPARTIALReturn")]
        public string GETCUSTOMERSPARTIAL(string DBNAME, string VIEWNAME, string MYUNID) {
            object[] results = this.Invoke("GETCUSTOMERSPARTIAL", new object[] {
                        DBNAME,
                        VIEWNAME,
                        MYUNID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GETCUSTOMERSPARTIALAsync(string DBNAME, string VIEWNAME, string MYUNID) {
            this.GETCUSTOMERSPARTIALAsync(DBNAME, VIEWNAME, MYUNID, null);
        }
        
        /// <remarks/>
        public void GETCUSTOMERSPARTIALAsync(string DBNAME, string VIEWNAME, string MYUNID, object userState) {
            if ((this.GETCUSTOMERSPARTIALOperationCompleted == null)) {
                this.GETCUSTOMERSPARTIALOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETCUSTOMERSPARTIALOperationCompleted);
            }
            this.InvokeAsync("GETCUSTOMERSPARTIAL", new object[] {
                        DBNAME,
                        VIEWNAME,
                        MYUNID}, this.GETCUSTOMERSPARTIALOperationCompleted, userState);
        }
        
        private void OnGETCUSTOMERSPARTIALOperationCompleted(object arg) {
            if ((this.GETCUSTOMERSPARTIALCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETCUSTOMERSPARTIALCompleted(this, new GETCUSTOMERSPARTIALCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GETCUSTOMERSPARTIALCompletedEventHandler(object sender, GETCUSTOMERSPARTIALCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETCUSTOMERSPARTIALCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETCUSTOMERSPARTIALCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591